#!/bin/bash

#make sure fswatch is installed

#wget https://github.com/emcrisostomo/fswatch

#local

git config credential.helper store

#global

git config --global credential.helper store

git config credential.helper store

git push https://https://github.com/verissimusel/auto-git_credential.git
